name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings 
    - name: Fmt
      run: cargo fmt --check
  test-py:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rormula
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Create env
      run: python3 -m venv .venv
      run: . .venv/bin/activate
    - name: Build Rormula
      uses: PyO3/maturin-action@v1
      with:
        command: develop
        working-directory: rormula
    - name: Install Rormula
      run: pip install rormula/target/wheels/rormula-0.1.0-cp39-cp39-linux_x86_64.whl
    - name: Test
      run: pytest test
